language: cpp
sudo: true
dist: bionic
compiler:
  - clang
os:
  - linux
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
    packages:
      - cmake
      - clang-9
branches:
  only:
    - master
notifications:
  email: true

before_install:
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install -y clang
script:
  - export CC="$CC-9
  - export CXX="$CXX-9"
  - cmake .
  - cmake --build .
  - make test