language: cpp
sudo: false
dist: bionic
compiler:
  - gcc
os:
  - linux
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - cmake
      - g++-7
branches:
  only:
    - master
notifications:
  email: true

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake .
  - cmake --build .
  - make test