language: cpp
sudo: false
dist: bionic
compiler:
  - gcc
os:
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - cmake
branches:
  only:
    - master
notifications:
  email: true

script:
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake .
  - cmake --build .