language: cpp
sudo: false
dist: bionic
compiler:
  - clang
os:
  - linux
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
    packages:
      - cmake
      - clang
      - g++-7
branches:
  only:
    - master
notifications:
  email: true

script:
  - export CC=clang-9
  - export CXX=clang++-9
  - cmake .
  - cmake --build .
  - make test