language: cpp
sudo: false
dist: bionic
compiler:
  - gcc
os:
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
branches:
  only:
    - master
notifications:
  email: true

script:
  - cmake .
  - cmake --build .
  - make test